---
title: "A_percula_kimbe"
author: "Agneesh Barua"
date: "8/12/2021"
output: html_document
---

```{r,message=F}
library(tidyverse)
library(janitor)
library(ellipse)
library(edgeR)
library(DESeq2)
```

```{r,eval=F}
#### chunk is outdated. Look at local version ####
rbind(read_tsv("../results/SSPN7_S1/abundance.tsv") %>% select(target_id,est_counts) %>% mutate(sample="SS_1"),
read_tsv("../results/SSPN8_S1/abundance.tsv") %>% select(target_id,est_counts) %>% mutate(sample="SS_2"),
read_tsv("../results/SSPN9_S1/abundance.tsv") %>% select(target_id,est_counts) %>% mutate(sample="SS_3"),
read_tsv("../results/SSPN10_S1/abundance.tsv") %>% select(target_id,est_counts) %>% mutate(sample="HH_1"),
read_tsv("../results/SSPN11_S1/abundance.tsv") %>% select(target_id,est_counts) %>% mutate(sample="HH_2"),
read_tsv("../results/SSPN12_S1/abundance.tsv") %>% select(target_id,est_counts) %>% mutate(sample="HH_3"),
read_tsv("../results/SSPN13_S1/abundance.tsv") %>% select(target_id,est_counts) %>% mutate(sample="SH_1"),
read_tsv("../results/SSPN14_S1/abundance.tsv") %>% select(target_id,est_counts) %>% mutate(sample="SH_2"),
read_tsv("../results/SSPN15_S1/abundance.tsv") %>% select(target_id,est_counts) %>% mutate(sample="SH_3"),
read_tsv("../results/SSPN16_S1/abundance.tsv") %>% select(target_id,est_counts) %>% mutate(sample="HS_1"),
read_tsv("../results/SSPN17_S1/abundance.tsv") %>% select(target_id,est_counts) %>% mutate(sample="HS_2"),
read_tsv("../results/SSPN18_S1/abundance.tsv") %>% select(target_id,est_counts) %>% mutate(sample="HS_3")) %>%
  spread(sample,est_counts)->A.perula_dat

d<-A.perula_dat %>% column_to_rownames('target_id')
A.perula_dat %>% saveRDS("../results/A.percula_counts.RDS")
d %>% saveRDS("../results/A.percula_dat.csv")

#GGally::ggpairs(log10(d+1))
```

#Run from here
```{r}
d<-readRDS("./A.percula_dat_gene_id.RDS")
A.perula_dat<-readRDS("./A.percula_counts_gene_id.RDS")
```


### PCA
```{r}
d <- d[sort(rowSums(d, na.rm = T), decreasing = T, index.return = T)[[2]][1:5000],]
d <- log(d+1) %>% t() %>% dist()
fit <- MASS::isoMDS(d, k=2)
plotDat <- data.frame(x = fit$points[,1], y = fit$points[,2], sample = c(rep("SS",3),rep("HH",3),rep("SH",3),rep("HS",3)))
                                                                      

centroids <- aggregate(cbind(x,y) ~ sample, plotDat, mean)
conf.rgn  <- do.call(rbind, lapply(unique(plotDat$sample), function(t)
  data.frame(sample = as.character(t),
             ellipse(cov(plotDat[plotDat$sample == t, 1:2]),
                     centre=as.matrix(centroids[centroids$sample == t,2:3]),
                     level=0.95),
             stringsAsFactors=FALSE)))

tp2 <- ggplot(plotDat, aes(x,y,color = sample)) + geom_point(size=3) + theme_bw() + geom_path(data=conf.rgn) + xlab("NMDS Axis 1") + ylab("NMDS Axis 2")+ theme(legend.position = 'bottom')
tp2
```

```{r}
groups<-factor(c(rep("SS",3),
                 rep("HH",3),
                 rep("SH",3),
                 rep("HS",3)))
dge<-DGEList(A.perula_dat %>% column_to_rownames("target_id"), 
             group = groups, 
             genes = A.perula_dat$target_id)
dge
```

#### Preprosessing
```{r}
keep<- filterByExpr(dge, min.count = 5)                 
summary(keep)
dge<- dge[keep,,keep.lib.sizes = F]
```
#### Normalise using TMM: Done for removing compositional bias
```{r}
dge<-calcNormFactors(dge, method = "TMM")
dge$samples
```


```{r}
plotMD(cpm(dge, log = T),column =4)
plotMDS(dge)
```


#### Estimate dispersion {.tabset .tabset-fade}
```{r}
#to estimate dispersions with multiple factors we donstruct a design matrix. 0+ means not to include an intercept
design <- model.matrix(~0+group, dge$samples)
colnames(design)<-levels(dge$samples$group)
dge<-estimateDisp(dge, design, robust = T)
dge$common.dispersion
plotBCV(dge)
```

#### Determining quasi liklihood 
```{r}
fit<-glmQLFit(dge, design, robust = T)
head(fit$coefficients)
plotQLDisp(fit)
```

## Differential expression analysis
Only SS-SH, HH-HS, (SS-SH)-(HH-HS) possible
```{r}
con<-makeContrasts(HH-HS, levels = design)
qlf<- glmQLFTest(fit,contrast=con)
topTags(qlf) %>% view
#topTags(qlf) %>% as.data.frame() %>%  write_csv("./SS_SH_HH_HS_contrast.csv")

```
###### QLF-test
```{r}
summary(decideTests(qlf))
plotMD(qlf)
```