---
title: "Natacha's_gene_sets"
author: "Agneesh Barua"
date: "10/12/2021"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
A.per_dat_counts<-readRDS("./A.percula_tpm_gene_id.RDS")
A.oce_dat_counts<-readRDS("./A.oce_dat_tpm_gene_id.RDS")
sialic_acids<-read_csv("./Sialic_acids.csv")
metabolism<-read_csv("./Metabolism_gene_set.csv")

A.oce_metabolism<-A.oce_dat_counts %>% separate(gene_id, c("gene_id"),extra = 'drop') %>% filter(gene_id %in% metabolism$A.oce_gene_id)
A.oce_sialic_acids<-A.oce_dat_counts %>% separate(gene_id, c("gene_id"),extra = 'drop') %>% filter(gene_id %in% sialic_acids$A.oce_gene_id)

A.per_metabolisms<-A.per_dat_counts %>% separate(gene_id, c("gene_id"),extra = 'drop') %>% filter(gene_id %in% metabolism$A.per_gene_id)
A.per_sialic_acids<-A.per_dat_counts %>% separate(gene_id, c("gene_id"),extra = 'drop') %>% filter(gene_id %in% sialic_acids$A.per_gene_id)
```

```{r}
A.per_metabolisms %>% rename(A.per_gene_id = gene_id) %>% right_join(metabolism) %>% select(-A.oce_gene_id)->A.per_metabolisms
A.per_sialic_acids %>% rename(A.per_gene_id = gene_id) %>% right_join(sialic_acids) %>% select(-A.oce_gene_id)->A.per_sialic_acids

A.oce_metabolism %>% rename(A.oce_gene_id = gene_id) %>% right_join(metabolism) %>% select(-A.per_gene_id)->A.oce_metabolisms
A.oce_sialic_acids %>% rename(A.oce_gene_id = gene_id) %>% right_join(sialic_acids) %>% select(-A.per_gene_id)->A.oce_sialic_acids



zero_24hr_anemone<-readRDS("zero_24hr_anemone_comp.RDS") %>% rownames_to_column("gene_id")
zero_24hr_anemone_top<-readRDS("topTags_0_24hr_with_anemone.RDS")
SS_SH<-readRDS("SS_SH_comp.RDS") %>% rownames_to_column("gene_id")
HH_HS<-readRDS("HH_HS_comp.RDS") %>% rownames_to_column("gene_id")
SSSH_HHHS<-readRDS("SSSH_HHHS_comp.RDS") %>% rownames_to_column("gene_id")
```

```{r}

zero_24hr_anemone %>% separate(gene_id, c("gene_id"),extra = 'drop') %>% filter(gene_id %in% A.oce_metabolisms$A.oce_gene_id) %>% view
SS_SH
```
