---
title: "Making_plots"
author: "Agneesh Barua"
date: "10/8/2021"
output: html_document
---
```{r,message=F}
library(tidyverse)
library(janitor)
library(ellipse)
library(edgeR)
library(DESeq2)
```

## Get data files
```{r}
A.per_dat_counts<-readRDS("./A.percula_counts_gene_id.RDS")
A.oce_dat_counts<-readRDS("./A.oce_dat_counts_gene_id.RDS")
sialic_acids<-read_csv("./Sialic_acids.csv")
metabolism<-read_csv("./Metabolism_gene_set.csv")

A.oce_metabolism<-A.oce_dat_counts %>% separate(gene_id, c("gene_id"),extra = 'drop') %>% filter(gene_id %in% metabolism$A.oce_gene_id)
A.oce_sialic_acids<-A.oce_dat_counts %>% separate(gene_id, c("gene_id"),extra = 'drop') %>% filter(gene_id %in% sialic_acids$A.oce_gene_id)

A.per_metabolisms<-A.per_dat_counts %>% separate(gene_id, c("gene_id"),extra = 'drop') %>% filter(gene_id %in% metabolism$A.per_gene_id)
A.per_sialic_acids<-A.per_dat_counts %>% separate(gene_id, c("gene_id"),extra = 'drop') %>% filter(gene_id %in% sialic_acids$A.per_gene_id)

```

## format datasets
```{r}
#for ocellaris
groups<-factor(c(rep("zero_hr",156),
                 rep("Twenty_four_hrs_no_anemone",156),
                 rep("Twenty_four_hrs_with_anemone",156),
                 rep("Forty_eight_hrs_with_no_anemone",156),
                 rep("Forty_eight_hrs_with_anemone",156)))

A.oce_melt_metabolism<-A.oce_metabolism %>% reshape2::melt() %>% mutate(group=groups) %>% select(-variable)

groups<-factor(c(rep("zero_hr",81),
                 rep("Twenty_four_hrs_no_anemone",81),
                 rep("Twenty_four_hrs_with_anemone",81),
                 rep("Forty_eight_hrs_with_no_anemone",81),
                 rep("Forty_eight_hrs_with_anemone",81)))
A.oce_melt_sialic<-A.oce_sialic_acids %>% reshape2::melt() %>% mutate(group=groups) %>% select(-variable)

#for percula
groups<-factor(c(rep("SS",141),
                 rep("HH",141),
                 rep("SH",141),
                 rep("HS",141)))

A.per_melt_metabolism<-A.per_metabolisms %>% reshape2::melt() %>% mutate(group=groups) %>% select(-variable)

groups<-factor(c(rep("SS",84),
                 rep("HH",84),
                 rep("SH",84),
                 rep("HS",84)))
A.per_sialic<-A.per_sialic_acids %>% reshape2::melt() %>% mutate(group=groups) %>% select(-variable)
```

```{r, plot function}
t<-A.oce_melt_metabolism %>% arrange(gene_id)

ggplot(t, aes(x = factor(gene_id), y = log(value), fill = group))+
  geom_boxplot(alpha = 0.8)+
  scale_fill_brewer(palette="Set1")+
  geom_jitter()


```
