---
title: "Recruits_exp"
author: "Agneesh Barua"
date: "10/13/2021"
output: html_document
---

```{r setup, message=F}
library(tidyverse)
library(janitor)
library(ellipse)
library(edgeR)
library(DESeq2)
```

```{r,eval=F}
A.p<-read_csv("../A.percula_transcript_id_gene_ids.csv",col_names = c("target_id","gene_id"))
rbind(read_tsv("../results/SSPN5_S1_r_St/abundance.tsv") %>% select(target_id,est_counts) %>% left_join(A.p) %>% group_by(gene_id) %>% summarise(est_counts = sum(est_counts)) %>% mutate(sample="St_1"),
read_tsv("../results/SSPN6_S1_r_St/abundance.tsv") %>% select(target_id,est_counts) %>% left_join(A.p) %>% group_by(gene_id) %>% summarise(est_counts = sum(est_counts)) %>% mutate(sample="St_2"),
read_tsv("../results/SSPN22_S1_r_St/abundance.tsv") %>% select(target_id,est_counts) %>% left_join(A.p) %>% group_by(gene_id) %>% summarise(est_counts = sum(est_counts)) %>% mutate(sample="St_3"),
read_tsv("../results/SSPN19_S1_r_Ht/abundance.tsv") %>% select(target_id,est_counts) %>% left_join(A.p) %>% group_by(gene_id) %>% summarise(est_counts = sum(est_counts)) %>% mutate(sample="Ht_1"),
read_tsv("../results/SSPN20_S1_r_Ht/abundance.tsv") %>% select(target_id,est_counts) %>% left_join(A.p) %>% group_by(gene_id) %>% summarise(est_counts = sum(est_counts)) %>% mutate(sample="Ht_2"),
read_tsv("../results/SSPN21_S1_r_Ht/abundance.tsv") %>% select(target_id,est_counts) %>% left_join(A.p) %>% group_by(gene_id) %>% summarise(est_counts = sum(est_counts)) %>% mutate(sample="Ht_3")) %>%
  spread(sample,est_counts)->recruits_dat

d<-recruits_dat %>% column_to_rownames('gene_id')
recruits_dat %>% saveRDS("../results/recruits_gene_id.RDS")
```

```{r}
d<-readRDS("../RDS_files/recruits_gene_id.RDS") %>% column_to_rownames('gene_id')
d <- d[sort(rowSums(d, na.rm = T), decreasing = T, index.return = T)[[2]][1:5000],]
d <- log(d+1) %>% t() %>% dist()
fit <- MASS::isoMDS(d, k=2)
plotDat <- data.frame(x = fit$points[,1], y = fit$points[,2], sample = c(rep("Ht",3),rep("St",3)))
                                                                      

centroids <- aggregate(cbind(x,y) ~ sample, plotDat, mean)
conf.rgn  <- do.call(rbind, lapply(unique(plotDat$sample), function(t)
  data.frame(sample = as.character(t),
             ellipse(cov(plotDat[plotDat$sample == t, 1:2]),
                     centre=as.matrix(centroids[centroids$sample == t,2:3]),
                     level=0.95),
             stringsAsFactors=FALSE)))

tp2 <- ggplot(plotDat, aes(x,y,color = sample)) + geom_point(size=3) + theme_bw() + geom_path(data=conf.rgn) + xlab("NMDS Axis 1") + ylab("NMDS Axis 2")+ theme(legend.position = 'bottom')
tp2
```

```{r}
recruits_dat<-readRDS("../RDS_files/recruits_gene_id.RDS")
groups<-factor(c(rep("Ht",3),
                 rep("St",3)))
dge<-DGEList(recruits_dat %>% column_to_rownames("gene_id"), 
             group = groups, 
             genes = recruits_dat$gene_id)
dge
```

```{r}
keep<- filterByExpr(dge, min.count = 5)                 
summary(keep)
dge<- dge[keep,,keep.lib.sizes = F]
```
#### Normalise using TMM: Done for removing compositional bias
```{r}
dge<-calcNormFactors(dge, method = "TMM")
dge$samples
```


```{r}
plotMD(cpm(dge, log = T),column =2)
plotMDS(dge)
```


#### Estimate dispersion {.tabset .tabset-fade}
```{r}
#to estimate dispersions with multiple factors we donstruct a design matrix. 0+ means not to include an intercept
design <- model.matrix(~0+group, dge$samples)
colnames(design)<-levels(dge$samples$group)
dge<-estimateDisp(dge, design, robust = T)
dge$common.dispersion
plotBCV(dge)
```

#### Determining quasi liklihood 
```{r}
fit<-glmQLFit(dge, design, robust = T)
head(fit$coefficients)
plotQLDisp(fit)
```

## Differential expression analysis
Only SS-SH, HH-HS, (SS-SH)-(HH-HS) possible
```{r}
con<-makeContrasts(Ht-St, levels = design)
qlf<- glmQLFTest(fit,contrast=con)
topTags(qlf,n = 45) %>% view
topTags(qlf,n = 20861) %>% as.data.frame() %>%  write_csv("./recruits_contrast.csv")

```
###### QLF-test
```{r}
summary(decideTests(qlf))
plotMD(qlf)
```


## Custom plots
```{r}
library(ggsci)
met<-read_csv("../metabolism_genes.csv",col_names = c("symbol","genes"))
ops<-read_csv("../opsin_genes.csv",col_names = c("symbol","genes"))
corts<-read_csv("../corticoids.csv",col_names = c("symbol","genes"))
th<-read_csv("../th_genes.csv",col_names = c("symbol","genes"))
sia<-read_csv("../sialic_genes.csv",col_names = c("symbol","genes"))

#met
d<-topTags(qlf,n = 20861) %>% as.data.frame() %>% separate(genes,c("genes"),extra = 'drop')
d<-left_join(d,met,by= "genes") %>%  select(genes,logFC,FDR,symbol)
d$diffexp<-"NO"
d$diffexp[d$logFC > 0.5 & d$FDR <= 0.05]<-"UP"
d$diffexp[d$logFC < -0.5 & d$FDR <= 0.05]<-"DOWN"

d %>% ggplot(aes(logFC,-log10(FDR),col = diffexp,label = symbol))+
  geom_point()+
  geom_text(size = 3,col = "black")+
  scale_color_startrek()+
  ggtitle("Metabolism genes")+
  theme_bw() -> met_plot

#Opsins
d<-topTags(qlf,n = 20861) %>% as.data.frame() %>% separate(genes,c("genes"),extra = 'drop')
d<-left_join(d,ops,by= "genes") %>%  select(genes,logFC,FDR,symbol)
d$diffexp<-"NO"
d$diffexp[d$logFC > 0.5 & d$FDR <= 0.05]<-"UP"
d$diffexp[d$logFC < -0.5 & d$FDR <= 0.05]<-"DOWN"

d %>% ggplot(aes(logFC,-log10(FDR),col = diffexp,label = symbol))+
  geom_point()+
  geom_text(size = 3,col = "black")+
  scale_color_startrek()+
  ggtitle("Opsin genes")+
  theme_bw() -> ops_plot

#th genes
d<-topTags(qlf,n = 20861) %>% as.data.frame() %>% separate(genes,c("genes"),extra = 'drop')
d<-left_join(d,th,by= "genes") %>%  select(genes,logFC,FDR,symbol)
d$diffexp<-"NO"
d$diffexp[d$logFC > 0.5 & d$FDR <= 0.05]<-"UP"
d$diffexp[d$logFC < -0.5 & d$FDR <= 0.05]<-"DOWN"

d %>% ggplot(aes(logFC,-log10(FDR),col = diffexp,label = symbol))+
  geom_point()+
  geom_text(size = 3,col = "black")+
  scale_color_startrek()+
  ggtitle("TH genes")+
  theme_bw() -> th_plot

#corts
d<-topTags(qlf,n = 20861) %>% as.data.frame() %>% separate(genes,c("genes"),extra = 'drop')
d<-left_join(d,sia,by= "genes") %>%  select(genes,logFC,FDR,symbol)
d$diffexp<-"NO"
d$diffexp[d$logFC > 0.5 & d$FDR <= 0.05]<-"UP"
d$diffexp[d$logFC < -0.5 & d$FDR <= 0.05]<-"DOWN"

d %>% ggplot(aes(logFC,-log10(FDR),col = diffexp,label = symbol))+
  geom_point()+
  geom_text(size = 3,col = "black")+
  scale_color_startrek()+
  ggtitle("Cortico genes")+
  theme_bw() -> cort_plot

#sialic
d<-topTags(qlf,n = 20861) %>% as.data.frame() %>% separate(genes,c("genes"),extra = 'drop')
d<-left_join(d,sia,by= "genes") %>%  select(genes,logFC,FDR,symbol)
d$diffexp<-"NO"
d$diffexp[d$logFC > 0.5 & d$FDR <= 0.05]<-"UP"
d$diffexp[d$logFC < -0.5 & d$FDR <= 0.05]<-"DOWN"

d %>% ggplot(aes(logFC,-log10(FDR),col = diffexp,label = symbol))+
  geom_point()+
  geom_text(size = 3,col = "black")+
  scale_color_startrek()+
  ggtitle("Sialic acid genes")+
  theme_bw() -> sia_plot
```

## Diff PCA
```{r}
library(ggfortify)
var_dat<-recruits_dat %>% column_to_rownames("gene_id")
g<-tibble(id = c(rep("Ht",3),rep("St",3)))

se<-SummarizedExperiment(vst(as.matrix(round(var_dat)),fitType = 'mean'),colData = g$id)

rv <- rowVars(assay(se))
select <- order(rv, decreasing=TRUE)[seq_len(min(1000, length(rv)))]
pca <- prcomp(t(assay(se)[select,]))
percentVar <- pca$sdev^2 / sum( pca$sdev^2 )


 pca$x %>% as_tibble %>% select(PC1,PC2) %>% mutate(s = g$id) %>% ggplot(aes(PC1,PC2,color = s))+
  geom_point(size = 4)+
  scale_color_ucscgb()+
  xlab(paste0("PC1 (", round(percentVar[1]*100),"%)"))+
  ylab(paste0("PC2 (", round(percentVar[2]*100),"%)"))+
  theme_bw() ->pc12
 
 pca$x %>% as_tibble %>% select(PC2,PC3) %>% mutate(s = g$id) %>% ggplot(aes(PC2,PC3,color = s))+
  geom_point(size = 4)+
  scale_color_ucscgb()+
  xlab(paste0("PC2 (", round(percentVar[2]*100),"%)"))+
  ylab(paste0("PC3 (", round(percentVar[3]*100),"%)"))+
  theme_bw() ->pc23
```

```{r}
#Met
var_dat<-recruits_dat %>% separate(gene_id,c("gene_id"),extra = 'drop') %>% filter(gene_id %in% met$genes) %>% column_to_rownames("gene_id")
g<-tibble(id = c(rep("Ht",3),rep("St",3)))

se<-SummarizedExperiment(varianceStabilizingTransformation(as.matrix(round(var_dat))),colData = g$id)

rv <- rowVars(assay(se))
select <- order(rv, decreasing=TRUE)[seq_len(min(1000, length(rv)))]
pca <- prcomp(t(assay(se)[select,]))
percentVar <- pca$sdev^2 / sum( pca$sdev^2 )


 pca$x %>% as_tibble %>% select(PC1,PC2) %>% mutate(s = g$id) %>% ggplot(aes(PC1,PC2,color = s))+
  geom_point(size = 4)+
  scale_color_ucscgb()+
  xlab(paste0("PC1 (", round(percentVar[1]*100),"%)"))+
  ylab(paste0("PC2 (", round(percentVar[2]*100),"%)"))+
  theme_bw() ->met_pc12
 
 pca$x %>% as_tibble %>% select(PC2,PC3) %>% mutate(s = g$id) %>% ggplot(aes(PC2,PC3,color = s))+
  geom_point(size = 4)+
  scale_color_ucscgb()+
  xlab(paste0("PC2 (", round(percentVar[2]*100),"%)"))+
  ylab(paste0("PC3 (", round(percentVar[3]*100),"%)"))+
  theme_bw() ->met_pc23

gridExtra::grid.arrange(met_pc12,met_pc23,nrow = 2)
```

```{r}
#Ops
var_dat<-recruits_dat %>% separate(gene_id,c("gene_id"),extra = 'drop') %>% filter(gene_id %in% ops$genes) %>% column_to_rownames("gene_id")
g<-tibble(id = c(rep("Ht",3),rep("St",3)))

se<-SummarizedExperiment(varianceStabilizingTransformation(as.matrix(round(var_dat))),colData = g$id)

rv <- rowVars(assay(se))
select <- order(rv, decreasing=TRUE)[seq_len(min(1000, length(rv)))]
pca <- prcomp(t(assay(se)[select,]))
percentVar <- pca$sdev^2 / sum( pca$sdev^2 )


 pca$x %>% as_tibble %>% select(PC1,PC2) %>% mutate(s = g$id) %>% ggplot(aes(PC1,PC2,color = s))+
  geom_point(size = 4)+
  scale_color_ucscgb()+
  xlab(paste0("PC1 (", round(percentVar[1]*100),"%)"))+
  ylab(paste0("PC2 (", round(percentVar[2]*100),"%)"))+
  theme_bw() ->ops_pc12
 
 pca$x %>% as_tibble %>% select(PC2,PC3) %>% mutate(s = g$id) %>% ggplot(aes(PC2,PC3,color = s))+
  geom_point(size = 4)+
  scale_color_ucscgb()+
  xlab(paste0("PC2 (", round(percentVar[2]*100),"%)"))+
  ylab(paste0("PC3 (", round(percentVar[3]*100),"%)"))+
  theme_bw() ->ops_pc23

gridExtra::grid.arrange(ops_pc12,ops_pc23,nrow = 2)
```

```{r}
#corts
var_dat<-recruits_dat %>% separate(gene_id,c("gene_id"),extra = 'drop') %>% filter(gene_id %in% corts$genes) %>% column_to_rownames("gene_id")
g<-tibble(id = c(rep("Ht",3),rep("St",3)))

se<-SummarizedExperiment(varianceStabilizingTransformation(as.matrix(round(var_dat))),colData = g$id)

rv <- rowVars(assay(se))
select <- order(rv, decreasing=TRUE)[seq_len(min(1000, length(rv)))]
pca <- prcomp(t(assay(se)[select,]))
percentVar <- pca$sdev^2 / sum( pca$sdev^2 )


 pca$x %>% as_tibble %>% select(PC1,PC2) %>% mutate(s = g$id) %>% ggplot(aes(PC1,PC2,color = s))+
  geom_point(size = 4)+
  scale_color_ucscgb()+
  xlab(paste0("PC1 (", round(percentVar[1]*100),"%)"))+
  ylab(paste0("PC2 (", round(percentVar[2]*100),"%)"))+
  theme_bw() ->corts_pc12
 
 pca$x %>% as_tibble %>% select(PC2,PC3) %>% mutate(s = g$id) %>% ggplot(aes(PC2,PC3,color = s))+
  geom_point(size = 4)+
  scale_color_ucscgb()+
  xlab(paste0("PC2 (", round(percentVar[2]*100),"%)"))+
  ylab(paste0("PC3 (", round(percentVar[3]*100),"%)"))+
  theme_bw() ->corts_pc23

gridExtra::grid.arrange(corts_pc12,corts_pc23,nrow = 2)
```

```{r}
#th
var_dat<-recruits_dat %>% separate(gene_id,c("gene_id"),extra = 'drop') %>% filter(gene_id %in% th$genes) %>% column_to_rownames("gene_id")
g<-tibble(id = c(rep("Ht",3),rep("St",3)))

se<-SummarizedExperiment(varianceStabilizingTransformation(as.matrix(round(var_dat))),colData = g$id)

rv <- rowVars(assay(se))
select <- order(rv, decreasing=TRUE)[seq_len(min(1000, length(rv)))]
pca <- prcomp(t(assay(se)[select,]))
percentVar <- pca$sdev^2 / sum( pca$sdev^2 )


 pca$x %>% as_tibble %>% select(PC1,PC2) %>% mutate(s = g$id) %>% ggplot(aes(PC1,PC2,color = s))+
  geom_point(size = 4)+
  scale_color_ucscgb()+
  xlab(paste0("PC1 (", round(percentVar[1]*100),"%)"))+
  ylab(paste0("PC2 (", round(percentVar[2]*100),"%)"))+
  theme_bw() ->th_pc12
 
 pca$x %>% as_tibble %>% select(PC2,PC3) %>% mutate(s = g$id) %>% ggplot(aes(PC2,PC3,color = s))+
  geom_point(size = 4)+
  scale_color_ucscgb()+
  xlab(paste0("PC2 (", round(percentVar[2]*100),"%)"))+
  ylab(paste0("PC3 (", round(percentVar[3]*100),"%)"))+
  theme_bw() ->th_pc23

gridExtra::grid.arrange(th_pc12,th_pc23,nrow = 2)
```

```{r}
#th
var_dat<-recruits_dat %>% separate(gene_id,c("gene_id"),extra = 'drop') %>% filter(gene_id %in% sia$genes) %>% column_to_rownames("gene_id")
g<-tibble(id = c(rep("Ht",3),rep("St",3)))

se<-SummarizedExperiment(varianceStabilizingTransformation(as.matrix(round(var_dat))),colData = g$id)

rv <- rowVars(assay(se))
select <- order(rv, decreasing=TRUE)[seq_len(min(1000, length(rv)))]
pca <- prcomp(t(assay(se)[select,]))
percentVar <- pca$sdev^2 / sum( pca$sdev^2 )


 pca$x %>% as_tibble %>% select(PC1,PC2) %>% mutate(s = g$id) %>% ggplot(aes(PC1,PC2,color = s))+
  geom_point(size = 4)+
  scale_color_ucscgb()+
  xlab(paste0("PC1 (", round(percentVar[1]*100),"%)"))+
  ylab(paste0("PC2 (", round(percentVar[2]*100),"%)"))+
  theme_bw() ->sia_pc12
 
 pca$x %>% as_tibble %>% select(PC2,PC3) %>% mutate(s = g$id) %>% ggplot(aes(PC2,PC3,color = s))+
  geom_point(size = 4)+
  scale_color_ucscgb()+
  xlab(paste0("PC2 (", round(percentVar[2]*100),"%)"))+
  ylab(paste0("PC3 (", round(percentVar[3]*100),"%)"))+
  theme_bw() ->sia_pc23

gridExtra::grid.arrange(sia_pc12,sia_pc23,nrow = 2)
```